CREATE DATABASE Filmes;

USE Filmes;

CREATE TABLE Genero
(
	IdGenero INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (50) NOT NULL 
);

CREATE TABLE Filme
(
	IdFilme INT PRIMARY KEY IDENTITY,
	IdGenero INT FOREIGN KEY REFERENCES Genero(IdGenero),
	NomeFilme VARCHAR (255) NOT NULL
);